# Generated by Django 5.1.1 on 2025-01-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='year',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='Semester',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='Semester',
            new_name='semester',
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.IntegerField(),
        ),
    ]
