# Generated by Django 5.1.1 on 2025-01-13 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_module_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp_images/')),
                ('file', models.FileField(upload_to='temp_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.branch')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject')),
            ],
        ),
    ]
