# Generated by Django 5.1.1 on 2025-01-13 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_tempmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.semester')),
            ],
        ),
        migrations.CreateModel(
            name='TempSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subjectcode', models.CharField(max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.branch')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.semester')),
            ],
        ),
    ]
