# Generated by Django 5.1.4 on 2025-01-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
